# Generated by Django 5.1.6 on 2025-02-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendendocriando', '0002_rename_imagens_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='descricao_url',
            field=models.URLField(null=True),
        ),
    ]
