# Generated by Django 5.1.6 on 2025-02-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprendendocriando', '0003_imagen_descricao_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='descricao_url',
        ),
    ]
