# Generated by Django 5.1.6 on 2025-02-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendendocriando', '0004_remove_imagen_descricao_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='descricao',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
